package com.collage.collage;

import static com.collage.collage.SqlConnect.con;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        bt_connect = new javax.swing.JButton();
        bt_disconnect = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        label_s_id = new javax.swing.JLabel();
        tf_s_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tf_F_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_L_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_phone = new javax.swing.JTextField();
        bt_insert = new javax.swing.JButton();
        bt_update = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_student = new javax.swing.JTable();
        bt_refresh = new javax.swing.JButton();
        bt_search = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tf_ins_I_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_ins_F_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_ins_L_name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_ins_phone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_ins_d_name_fk = new javax.swing.JTextField();
        bt_ins_insert = new javax.swing.JButton();
        bt_ins_update = new javax.swing.JButton();
        bt_ins_delete = new javax.swing.JButton();
        bt_ins_search = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_instructors = new javax.swing.JTable();
        bt_ins_refresh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_crs_C_id = new javax.swing.JTextField();
        tf_crs_C_name = new javax.swing.JTextField();
        tf_crs_duration = new javax.swing.JTextField();
        tf_crs_I_id_fk = new javax.swing.JTextField();
        bt_crs_insert = new javax.swing.JButton();
        bt_crs_update = new javax.swing.JButton();
        bt_crs_delete = new javax.swing.JButton();
        bt_crs_search = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_courses = new javax.swing.JTable();
        bt_crs_refresh = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_dep_D_name = new javax.swing.JTextField();
        tf_dep_location = new javax.swing.JTextField();
        tf_dep_id_head = new javax.swing.JTextField();
        bt_dep_insert = new javax.swing.JButton();
        bt_dep_update = new javax.swing.JButton();
        bt_dep_delete = new javax.swing.JButton();
        bt_dep_search = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_department = new javax.swing.JTable();
        bt_dep_refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_connect.setText("Conntect");
        bt_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_connectActionPerformed(evt);
            }
        });

        bt_disconnect.setText("Disconnect");
        bt_disconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_disconnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(bt_connect, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(bt_disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_connect, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Home", jPanel5);

        label_s_id.setText("s_id");

        jLabel1.setText("F_name");

        jLabel2.setText("L_name");

        jLabel3.setText("Phone");

        bt_insert.setText("Insert");
        bt_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_insertActionPerformed(evt);
            }
        });

        bt_update.setText("Update");
        bt_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_updateActionPerformed(evt);
            }
        });

        bt_delete.setText("Delete");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });

        table_student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "s_id", "F_name", "L_name", "phone"
            }
        ));
        jScrollPane1.setViewportView(table_student);

        bt_refresh.setText("Refresh");
        bt_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_refreshActionPerformed();
            }
        });

        bt_search.setText("Search");
        bt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_s_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_delete)
                    .addComponent(bt_update)
                    .addComponent(bt_insert)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_s_id)
                        .addComponent(tf_F_name)
                        .addComponent(tf_L_name)
                        .addComponent(tf_phone, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                    .addComponent(bt_search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_refresh)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_s_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_s_id))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_F_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_L_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(bt_insert)
                .addGap(18, 18, 18)
                .addComponent(bt_update)
                .addGap(18, 18, 18)
                .addComponent(bt_delete)
                .addGap(18, 18, 18)
                .addComponent(bt_search)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_refresh)
                .addGap(0, 84, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Student", jPanel1);

        jLabel4.setText("I_id");

        tf_ins_I_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ins_I_idActionPerformed(evt);
            }
        });

        jLabel5.setText("F_name");

        jLabel6.setText("L_name");

        jLabel7.setText("phone");

        jLabel8.setText("d_name_fk");

        bt_ins_insert.setText("Insert");
        bt_ins_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ins_insertActionPerformed(evt);
            }
        });

        bt_ins_update.setText("Update");
        bt_ins_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ins_updateActionPerformed(evt);
            }
        });

        bt_ins_delete.setText("Delete");
        bt_ins_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ins_deleteActionPerformed(evt);
            }
        });

        bt_ins_search.setText("Search");
        bt_ins_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ins_searchActionPerformed(evt);
            }
        });

        table_instructors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "I_id", "F_name", "L_name", "phone", "d_name_fk"
            }
        ));
        jScrollPane2.setViewportView(table_instructors);

        bt_ins_refresh.setText("Refresh");
        bt_ins_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ins_refreshActionPerformed();
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_ins_search)
                    .addComponent(bt_ins_delete)
                    .addComponent(bt_ins_update)
                    .addComponent(bt_ins_insert)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_ins_I_id)
                        .addComponent(tf_ins_F_name)
                        .addComponent(tf_ins_L_name)
                        .addComponent(tf_ins_phone)
                        .addComponent(tf_ins_d_name_fk, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_ins_refresh))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_ins_I_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_ins_F_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tf_ins_L_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_ins_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tf_ins_d_name_fk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(bt_ins_insert)
                        .addGap(18, 18, 18)
                        .addComponent(bt_ins_update)
                        .addGap(18, 18, 18)
                        .addComponent(bt_ins_delete))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_ins_search)
                    .addComponent(bt_ins_refresh))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Instructors", jPanel3);

        jLabel9.setText("C_id");

        jLabel10.setText("C_name");

        jLabel11.setText("duration");

        jLabel12.setText("I_id_fk");

        bt_crs_insert.setText("Insert");
        bt_crs_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crs_insertActionPerformed(evt);
            }
        });

        bt_crs_update.setText("Update");
        bt_crs_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crs_updateActionPerformed(evt);
            }
        });

        bt_crs_delete.setText("Delete");
        bt_crs_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crs_deleteActionPerformed(evt);
            }
        });

        bt_crs_search.setText("Search");
        bt_crs_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crs_searchActionPerformed(evt);
            }
        });

        table_courses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "C_id", "C_name", "duration", "I_id_fk"
            }
        ));
        jScrollPane3.setViewportView(table_courses);

        bt_crs_refresh.setText("Refresh");
        bt_crs_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crs_refreshActionPerformed();
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_crs_search)
                    .addComponent(bt_crs_delete)
                    .addComponent(bt_crs_update)
                    .addComponent(bt_crs_insert)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_crs_C_id)
                        .addComponent(tf_crs_C_name)
                        .addComponent(tf_crs_duration)
                        .addComponent(tf_crs_I_id_fk, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_crs_refresh)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tf_crs_C_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tf_crs_C_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tf_crs_duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tf_crs_I_id_fk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(bt_crs_insert)
                        .addGap(18, 18, 18)
                        .addComponent(bt_crs_update)
                        .addGap(18, 18, 18)
                        .addComponent(bt_crs_delete))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_crs_search)
                    .addComponent(bt_crs_refresh))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Courses", jPanel2);

        jLabel13.setText("D_name");

        jLabel14.setText("location");

        jLabel15.setText("id_head");

        bt_dep_insert.setText("Insert");
        bt_dep_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_dep_insertActionPerformed(evt);
            }
        });

        bt_dep_update.setText("update");
        bt_dep_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_dep_updateActionPerformed(evt);
            }
        });

        bt_dep_delete.setText("delete");
        bt_dep_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_dep_deleteActionPerformed(evt);
            }
        });

        bt_dep_search.setText("search");
        bt_dep_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_dep_searchActionPerformed(evt);
            }
        });

        table_department.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "D_name", "location", "id_head"
            }
        ));
        jScrollPane4.setViewportView(table_department);

        bt_dep_refresh.setText("Refresh");
        bt_dep_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_dep_refreshActionPerformed();
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_dep_search)
                    .addComponent(bt_dep_delete)
                    .addComponent(bt_dep_update)
                    .addComponent(bt_dep_insert)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_dep_D_name)
                        .addComponent(tf_dep_location)
                        .addComponent(tf_dep_id_head, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_dep_refresh))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tf_dep_D_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tf_dep_location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tf_dep_id_head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addComponent(bt_dep_insert)
                        .addGap(18, 18, 18)
                        .addComponent(bt_dep_update)
                        .addGap(18, 18, 18)
                        .addComponent(bt_dep_delete))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_dep_search)
                    .addComponent(bt_dep_refresh))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Department", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_connectActionPerformed
        // TODO add your handling code here:
        SqlConnect.ConnectToSQL();
        bt_refreshActionPerformed();
        bt_ins_refreshActionPerformed();
        bt_crs_refreshActionPerformed();
        bt_dep_refreshActionPerformed();
        JOptionPane.showMessageDialog(this, "CONNECTED");
    }//GEN-LAST:event_bt_connectActionPerformed

    private void bt_disconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_disconnectActionPerformed
        // TODO add your handling code here:
        SqlConnect.Close();
        JOptionPane.showMessageDialog(this, "DISCONNECTED");
    }//GEN-LAST:event_bt_disconnectActionPerformed

    private void bt_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_insertActionPerformed
        // TODO add your handling code here:
        // Integer.valueOf(tf_s_id.getText())
        try {   System.out.println("insert into student values"+ "("+"'"+tf_F_name.getText()+"','"+tf_L_name.getText()+"','"+tf_phone.getText()+"'"+")");
                SqlConnect.executeNonquary("insert into student values"+ "("+"'"+tf_F_name.getText()+"','"+tf_L_name.getText()+"','"+tf_phone.getText()+"'"+")");
                System.out.println("Inserted");
                bt_refreshActionPerformed();
                //JOptionPane.showMessageDialog(this, "INSERTED");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_bt_insertActionPerformed

    private void bt_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_updateActionPerformed
        // TODO add your handling code here:
        // System.out.println("update student set F_name = '"+tf_F_name.getText()+"', L_name = '"+tf_L_name.getText()+"', phone = '"+tf_phone.getText()+"'");
        SqlConnect.executeNonquary("update student set F_name = '"+tf_F_name.getText()+"', L_name = '"+tf_L_name.getText()+"', phone = '"+tf_phone.getText()+"' where s_id = "+String.valueOf(tf_s_id.getText()));
        //JOptionPane.showMessageDialog(this, "UPDATED");
    }//GEN-LAST:event_bt_updateActionPerformed

    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed
        // TODO add your handling code here:
        SqlConnect.executeNonquary("delete from student where s_id ="+String.valueOf(tf_s_id.getText()));
        bt_refreshActionPerformed();
                //JOptionPane.showMessageDialog(this, "DELETED");
                System.out.println("DELETED");

    }//GEN-LAST:event_bt_deleteActionPerformed


// java.awt.event.ActionEvent evt
    private void bt_refreshActionPerformed() {//GEN-FIRST:event_bt_refreshActionPerformed
            // TODO add your handling code here:
            try{
            DefaultTableModel student_tblModel = (DefaultTableModel) table_student.getModel();
            student_tblModel.setRowCount(0);
            String sql = "select * from student";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);  
            while(rs.next()){
                String str_s_id = String.valueOf(rs.getInt("s_id"));
                String str_F_name = rs.getString("F_name");
                String str_L_name = rs.getString("L_name");
                String str_phone = rs.getString("phone"); 
                String tbdata [] = {str_s_id,str_F_name,str_L_name,str_phone};
                
                student_tblModel.addRow(tbdata);
            }           
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_bt_refreshActionPerformed

    private void bt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_searchActionPerformed
        // TODO add your handling code here:
                    try{
            DefaultTableModel student_tblModel = (DefaultTableModel) table_student.getModel();
            student_tblModel.setRowCount(0);
            String sql = "select * from student where s_id = "+String.valueOf(tf_s_id.getText());
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);  
            while(rs.next()){
                String str_s_id = String.valueOf(rs.getInt("s_id"));
                String str_F_name = rs.getString("F_name");
                String str_L_name = rs.getString("L_name");
                String str_phone = rs.getString("phone"); 
                String tbdata [] = {str_s_id,str_F_name,str_L_name,str_phone};
                
                student_tblModel.addRow(tbdata);
            }           
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_bt_searchActionPerformed

    private void tf_ins_I_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ins_I_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ins_I_idActionPerformed

    private void bt_ins_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ins_insertActionPerformed
        // TODO add your handling code here:
                try {   System.out.println("insert into instructors values"+ "("+"'"+tf_ins_F_name.getText()+"','"+tf_ins_L_name.getText()+"','"+tf_ins_phone.getText()+"','"+tf_ins_d_name_fk.getText()+"')");
                SqlConnect.executeNonquary("insert into instructors values"+ "("+"'"+tf_ins_F_name.getText()+"','"+tf_ins_L_name.getText()+"','"+tf_ins_phone.getText()+"','"+tf_ins_d_name_fk.getText()+"')");
                System.out.println("Inserted");
                bt_ins_refreshActionPerformed();
                //JOptionPane.showMessageDialog(this, "INSTRUCTOR INSERTED");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_bt_ins_insertActionPerformed

    private void bt_ins_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ins_updateActionPerformed
        // TODO add your handling code here:
        SqlConnect.executeNonquary("update instructors set F_name = '"+tf_ins_F_name.getText()+"', L_name = '"+tf_ins_L_name.getText()+"', phone = '"+tf_ins_phone.getText()+"', d_name_fk= '"+tf_ins_d_name_fk.getText()+"' where I_id = "+String.valueOf(tf_ins_I_id.getText()));
        bt_ins_refreshActionPerformed();
        //JOptionPane.showMessageDialog(this, "INSTRUCTOR UPDATED");
    }//GEN-LAST:event_bt_ins_updateActionPerformed

    private void bt_ins_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ins_deleteActionPerformed
        // TODO add your handling code here:
                SqlConnect.executeNonquary("delete from instructors where I_id ="+String.valueOf(tf_ins_I_id.getText()));
                bt_ins_refreshActionPerformed();
                //JOptionPane.showMessageDialog(this, "INSTRUCTOR DELETED");
                System.out.println("INSTRUCTOR DELETED");
    }//GEN-LAST:event_bt_ins_deleteActionPerformed

    private void bt_ins_refreshActionPerformed() {//GEN-FIRST:event_bt_ins_refreshActionPerformed
        // TODO add your handling code here:
                    try{
            DefaultTableModel instructors_tblModel = (DefaultTableModel) table_instructors.getModel();
            instructors_tblModel.setRowCount(0);
            String sql = "select * from instructors";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);  
            while(rs.next()){
                String str_ins_I_id = String.valueOf(rs.getInt("I_id"));
                String str_ins_F_name = rs.getString("F_name");
                String str_ins_L_name = rs.getString("L_name");
                String str_ins_phone = rs.getString("phone");
                String str_ins_d_name_fk = rs.getString("d_name_fk");
                String tbdata [] = {str_ins_I_id,str_ins_F_name,str_ins_L_name,str_ins_phone,str_ins_d_name_fk};
                
                instructors_tblModel.addRow(tbdata);
            }           
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_bt_ins_refreshActionPerformed

    private void bt_ins_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ins_searchActionPerformed
        // TODO add your handling code here:
                            try{
            DefaultTableModel instructors_tblModel = (DefaultTableModel) table_instructors.getModel();
            instructors_tblModel.setRowCount(0);
            String sql = "select * from instructors where I_id = "+String.valueOf(tf_ins_I_id.getText());
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);  
            while(rs.next()){
                String str_ins_I_id = String.valueOf(rs.getInt("I_id"));
                String str_ins_F_name = rs.getString("F_name");
                String str_ins_L_name = rs.getString("L_name");
                String str_ins_phone = rs.getString("phone");
                String str_ins_d_name_fk = rs.getString("d_name_fk");
                String tbdata [] = {str_ins_I_id,str_ins_F_name,str_ins_L_name,str_ins_phone,str_ins_d_name_fk};
                
                instructors_tblModel.addRow(tbdata);
            }           
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_bt_ins_searchActionPerformed

    private void bt_crs_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crs_insertActionPerformed
        // TODO add your handling code here:
        try {   System.out.println("insert into courses values"+ "("+"'"+tf_crs_C_name.getText()+"','"+tf_crs_duration.getText()+"',"+Integer.valueOf(tf_crs_I_id_fk.getText())+")");
        SqlConnect.executeNonquary("insert into courses values"+ "("+"'"+tf_crs_C_name.getText()+"','"+tf_crs_duration.getText()+"',"+Integer.valueOf(tf_crs_I_id_fk.getText())+")");
        System.out.println("Inserted");
        bt_crs_refreshActionPerformed();
        //JOptionPane.showMessageDialog(this, "INSTRUCTOR INSERTED");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_bt_crs_insertActionPerformed

    private void bt_crs_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crs_updateActionPerformed
        // TODO add your handling code here:
        SqlConnect.executeNonquary("update courses set C_name = '"+tf_crs_C_name.getText()+"', duration = '"+tf_crs_duration.getText()+"', I_id_fk = "+Integer.valueOf(tf_crs_I_id_fk.getText())+" where c_id = "+String.valueOf(tf_crs_C_id.getText()));
        bt_crs_refreshActionPerformed();
        //JOptionPane.showMessageDialog(this, "Course UPDATED");
    }//GEN-LAST:event_bt_crs_updateActionPerformed

    private void bt_crs_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crs_deleteActionPerformed
        // TODO add your handling code here:
                SqlConnect.executeNonquary("delete from courses where C_id ="+String.valueOf(tf_crs_C_id.getText()));
                bt_crs_refreshActionPerformed();
                //JOptionPane.showMessageDialog(this, "DELETED");
                System.out.println("DELETED");
    }//GEN-LAST:event_bt_crs_deleteActionPerformed

    private void bt_crs_refreshActionPerformed() {//GEN-FIRST:event_bt_crs_refreshActionPerformed
        // TODO add your handling code here:
            try{
            DefaultTableModel courses_tblModel = (DefaultTableModel) table_courses.getModel();
            courses_tblModel.setRowCount(0);
            String sql = "select * from courses";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);  
            while(rs.next()){
                String str_crs_C_id = String.valueOf(rs.getInt("c_id"));
                String str_crs_C_name = rs.getString("c_name");
                String str_crs_duration = rs.getString("duration");
                String str_crs_I_id_fk = String.valueOf(rs.getInt("I_id_fk"));
                String tbdata [] = {str_crs_C_id,str_crs_C_name,str_crs_duration,str_crs_I_id_fk};
                
                courses_tblModel.addRow(tbdata);
            }           
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
    }//GEN-LAST:event_bt_crs_refreshActionPerformed

    private void bt_crs_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crs_searchActionPerformed
        // TODO add your handling code here:
                                    try{
            DefaultTableModel courses_tblModel = (DefaultTableModel) table_courses.getModel();
            courses_tblModel.setRowCount(0);
            String sql = "select * from courses where C_id = "+String.valueOf(tf_crs_C_id.getText());
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);  
            while(rs.next()){
                String str_crs_C_id = String.valueOf(rs.getInt("c_id"));
                String str_crs_C_name = rs.getString("c_name");
                String str_crs_duration = rs.getString("duration");
                String str_crs_I_id_fk = String.valueOf(rs.getInt("I_id_fk"));
                String tbdata [] = {str_crs_C_id,str_crs_C_name,str_crs_duration,str_crs_I_id_fk};
                
                courses_tblModel.addRow(tbdata);
            }           
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_bt_crs_searchActionPerformed

    private void bt_dep_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_dep_insertActionPerformed
        // TODO add your handling code here:
        try {   System.out.println("insert into department values"+ "("+"'"+tf_dep_D_name.getText()+"','"+tf_dep_location.getText()+"',"+Integer.valueOf(tf_dep_id_head.getText())+")");
        SqlConnect.executeNonquary("insert into department values"+ "("+"'"+tf_dep_D_name.getText()+"','"+tf_dep_location.getText()+"',"+Integer.valueOf(tf_dep_id_head.getText())+")");
        bt_dep_refreshActionPerformed();
        System.out.println("Inserted");
        //JOptionPane.showMessageDialog(this, "INSTRUCTOR INSERTED");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_bt_dep_insertActionPerformed

    private void bt_dep_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_dep_updateActionPerformed
                // TODO add your handling code here:
                // D_name = '"+tf_crs_C_name.getText()
                System.out.println("update department set location = '"+tf_dep_location.getText()+"', id_head = "+Integer.valueOf(tf_dep_id_head.getText())+ " where D_name = '"+tf_dep_D_name.getText()+"'");
                SqlConnect.executeNonquary("update department set location = '"+tf_dep_location.getText()+"', id_head = "+Integer.valueOf(tf_dep_id_head.getText())+ "where D_name = '"+tf_dep_D_name.getText()+"'");
                bt_dep_refreshActionPerformed();
                //JOptionPane.showMessageDialog(this, "Course UPDATED");  
    }//GEN-LAST:event_bt_dep_updateActionPerformed

    private void bt_dep_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_dep_deleteActionPerformed
        // TODO add your handling code here:
        SqlConnect.executeNonquary("delete from department where D_name = '"+tf_dep_D_name.getText()+"'");
        bt_dep_refreshActionPerformed();
    }//GEN-LAST:event_bt_dep_deleteActionPerformed

    private void bt_dep_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_dep_searchActionPerformed
        // TODO add your handling code here:
                                            try{
            DefaultTableModel department_tblModel = (DefaultTableModel) table_department.getModel();
            department_tblModel.setRowCount(0);
            String sql = "select * from department where D_name = "+"'"+tf_dep_D_name.getText()+"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);  
            while(rs.next()){
                //String str_crs_C_id = String.valueOf(rs.getInt("c_id"));
                String str_dep_D_name = rs.getString("D_name");
                String str_dep_location = rs.getString("location");
                String str_dep_id_head = String.valueOf(rs.getInt("id_head"));
                String tbdata [] = {str_dep_D_name,str_dep_location,str_dep_id_head};
                
                department_tblModel.addRow(tbdata);
            }           
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_bt_dep_searchActionPerformed

    private void bt_dep_refreshActionPerformed() {                                               
        // TODO add your handling code here:
            try{
            DefaultTableModel department_tblModel = (DefaultTableModel) table_department.getModel();
            department_tblModel.setRowCount(0);
            String sql = "select * from department";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);  
            while(rs.next()){
                //String str_crs_C_id = String.valueOf(rs.getInt("c_id"));
                String str_dep_D_name = rs.getString("D_name");
                String str_dep_location = rs.getString("location");
                String str_dep_id_head = String.valueOf(rs.getInt("id_head"));
                String tbdata [] = {str_dep_D_name,str_dep_location,str_dep_id_head};
                
                department_tblModel.addRow(tbdata);
            }           
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }                                                                                         


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_connect;
    private javax.swing.JButton bt_crs_delete;
    private javax.swing.JButton bt_crs_insert;
    private javax.swing.JButton bt_crs_refresh;
    private javax.swing.JButton bt_crs_search;
    private javax.swing.JButton bt_crs_update;
    private javax.swing.JButton bt_delete;
    private javax.swing.JButton bt_dep_delete;
    private javax.swing.JButton bt_dep_insert;
    private javax.swing.JButton bt_dep_refresh;
    private javax.swing.JButton bt_dep_search;
    private javax.swing.JButton bt_dep_update;
    private javax.swing.JButton bt_disconnect;
    private javax.swing.JButton bt_ins_delete;
    private javax.swing.JButton bt_ins_insert;
    private javax.swing.JButton bt_ins_refresh;
    private javax.swing.JButton bt_ins_search;
    private javax.swing.JButton bt_ins_update;
    private javax.swing.JButton bt_insert;
    private javax.swing.JButton bt_refresh;
    private javax.swing.JButton bt_search;
    private javax.swing.JButton bt_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel label_s_id;
    private javax.swing.JTable table_courses;
    private javax.swing.JTable table_department;
    private javax.swing.JTable table_instructors;
    private javax.swing.JTable table_student;
    private javax.swing.JTextField tf_F_name;
    private javax.swing.JTextField tf_L_name;
    private javax.swing.JTextField tf_crs_C_id;
    private javax.swing.JTextField tf_crs_C_name;
    private javax.swing.JTextField tf_crs_I_id_fk;
    private javax.swing.JTextField tf_crs_duration;
    private javax.swing.JTextField tf_dep_D_name;
    private javax.swing.JTextField tf_dep_id_head;
    private javax.swing.JTextField tf_dep_location;
    private javax.swing.JTextField tf_ins_F_name;
    private javax.swing.JTextField tf_ins_I_id;
    private javax.swing.JTextField tf_ins_L_name;
    private javax.swing.JTextField tf_ins_d_name_fk;
    private javax.swing.JTextField tf_ins_phone;
    private javax.swing.JTextField tf_phone;
    private javax.swing.JTextField tf_s_id;
    // End of variables declaration//GEN-END:variables
}
